import type { MonitoringTypeSchema } from "../monitoring-schema";

export const httpSchema: MonitoringTypeSchema = {
  type: "http",
  title: { en: "HTTP(S)", fa: "HTTP(S)" },
  description: { en: "HTTP/HTTPS availability and response", fa: "دسترس‌پذیری و پاسخ HTTP/HTTPS" },
  target: {
    label: { en: "Address", fa: "آدرس" },
    widget: "text",
    key: "url",
    placeholder: "https://api.example.com",
  },
  execution: {
    minimumIntervalSeconds: 10,
    defaultIntervalSeconds: 60,
    defaultTimeoutMillis: 10000,
    defaultRetries: 1,
  },
  configFields: [
    {
      key: "method",
      widget: "select",
      label: { en: "Method", fa: "متد" },
      section: "configuration",
      options: ["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"],
      defaultValue: "GET",
    },
    {
      key: "follow_redirects",
      widget: "switch",
      label: { en: "Follow redirects", fa: "دنبال کردن تغییر مسیر" },
      section: "configuration",
      defaultValue: true,
    },
    {
      key: "max_redirects",
      widget: "number",
      label: { en: "Max redirects", fa: "حداکثر تغییر مسیر" },
      section: "configuration",
      min: 0,
      max: 20,
      defaultValue: 5,
    },
    {
      key: "expected_status_codes",
      widget: "text",
      label: { en: "Expected status codes", fa: "کدهای وضعیت مورد انتظار" },
      help: { en: "Comma-separated, e.g. 200, 204", fa: "با ویرگول جدا کنید، مثلاً 200, 204" },
      section: "configuration",
      defaultValue: "200",
    },
    {
      key: "body_contains",
      widget: "text",
      label: { en: "Body contains", fa: "بدنه شامل" },
      help: { en: "The response body must contain this text", fa: "بدنه پاسخ باید شامل این متن باشد" },
      section: "configuration",
      defaultValue: "",
    },
    {
      key: "max_response_size_bytes",
      widget: "number",
      label: { en: "Max response size", fa: "حداکثر اندازه پاسخ" },
      section: "advanced",
      min: 1024,
      defaultValue: 10485760,
    },
    {
      key: "request_body",
      widget: "textarea",
      label: { en: "Request body", fa: "بدنه درخواست" },
      section: "configuration",
      defaultValue: "",
      visibleWhen: { field: "method", equalsAny: ["POST", "PUT", "PATCH"] },
    },
    {
      key: "headers",
      widget: "keyvalue",
      label: { en: "Headers", fa: "هدرها" },
      help: { en: "Use ${secret:name} to reference stored secrets", fa: "برای ارجاع به رازهای ذخیره‌شده از ${secret:name} استفاده کنید" },
      section: "advanced",
    },
  ],
  healthRules: [
    {
      key: "reachability",
      label: { en: "Availability", fa: "دسترس‌پذیری" },
      direction: "boolean",
      description: { en: "Endpoint unreachable is critical", fa: "عدم دسترسی به نقطه پایانی بحرانی است" },
      defaultEnabled: true,
    },
    {
      key: "response_time_ms",
      label: { en: "Response time", fa: "زمان پاسخ" },
      unit: "ms",
      direction: "higher_is_worse",
      description: { en: "Total request duration", fa: "مدت کل درخواست" },
      defaultEnabled: true,
      defaults: { warning: 2000, critical: 5000 },
    },
    {
      key: "ttfb_ms",
      label: { en: "TTFB", fa: "TTFB" },
      unit: "ms",
      direction: "higher_is_worse",
      description: { en: "Time to first byte", fa: "زمان تا اولین بایت" },
      defaultEnabled: false,
      defaults: { warning: 1000, critical: 3000 },
    },
    {
      key: "dns_duration_ms",
      label: { en: "DNS duration", fa: "مدت DNS" },
      unit: "ms",
      direction: "higher_is_worse",
      description: { en: "DNS resolution duration", fa: "مدت تفکیک DNS" },
      defaultEnabled: false,
      defaults: { warning: 500, critical: 2000 },
    },
    {
      key: "connect_duration_ms",
      label: { en: "Connect duration", fa: "مدت اتصال" },
      unit: "ms",
      direction: "higher_is_worse",
      description: { en: "TCP connect duration", fa: "مدت اتصال TCP" },
      defaultEnabled: false,
      defaults: { warning: 500, critical: 2000 },
    },
    {
      key: "tls_duration_ms",
      label: { en: "TLS duration", fa: "مدت TLS" },
      unit: "ms",
      direction: "higher_is_worse",
      description: { en: "TLS handshake duration", fa: "مدت دست‌داد TLS" },
      defaultEnabled: false,
      defaults: { warning: 500, critical: 2000 },
    },
    {
      key: "content_assertion",
      label: { en: "Content assertion", fa: "تطابق محتوا" },
      direction: "boolean",
      description: { en: "Body assertion mismatch is critical", fa: "عدم تطابق بدنه بحرانی است" },
      defaultEnabled: false,
    },
  ],
};
