import type { MonitoringTypeSchema } from "../monitoring-schema";

export const pingSchema: MonitoringTypeSchema = {
  type: "ping",
  title: { en: "Ping", fa: "پینگ" },
  description: { en: "ICMP reachability and latency", fa: "دسترس‌پذیری و تأخیر ICMP" },
  execution: {
    minimumIntervalSeconds: 10,
    defaultIntervalSeconds: 60,
    defaultTimeoutMillis: 5000,
    defaultRetries: 1,
  },
  configFields: [
    {
      key: "count",
      widget: "number",
      label: { en: "Packet count", fa: "تعداد بسته" },
      help: { en: "Number of ICMP echo requests per check", fa: "تعداد درخواست ICMP در هر بررسی" },
      section: "configuration",
      min: 1,
      max: 20,
      defaultValue: 4,
    },
    {
      key: "packet_interval_millis",
      widget: "number",
      label: { en: "Packet interval", fa: "فاصله بسته‌ها" },
      help: { en: "Delay between packets, in milliseconds", fa: "تأخیر بین بسته‌ها (میلی‌ثانیه)" },
      section: "configuration",
      min: 10,
      defaultValue: 200,
    },
    {
      key: "packet_size",
      widget: "number",
      label: { en: "Packet size", fa: "اندازه بسته" },
      section: "advanced",
      min: 24,
      max: 65507,
      defaultValue: 56,
    },
  ],
  healthRules: [
    {
      key: "reachability",
      label: { en: "Availability", fa: "دسترس‌پذیری" },
      direction: "boolean",
      description: { en: "Failure to reach the host is critical", fa: "عدم دسترسی به میزبان بحرانی است" },
      defaultEnabled: true,
    },
    {
      key: "latency_ms",
      label: { en: "Latency", fa: "تأخیر" },
      unit: "ms",
      direction: "higher_is_worse",
      description: { en: "Round-trip latency", fa: "تأخیر رفت‌وبرگشت" },
      defaultEnabled: true,
      defaults: { warning: 200, critical: 500 },
    },
    {
      key: "packet_loss",
      label: { en: "Packet loss", fa: "افت بسته" },
      unit: "%",
      direction: "higher_is_worse",
      description: { en: "Percentage of lost packets", fa: "درصد بسته‌های از دست رفته" },
      defaultEnabled: true,
      defaults: { warning: 5, critical: 20 },
    },
    {
      key: "jitter_ms",
      label: { en: "Jitter", fa: "نوسان" },
      unit: "ms",
      direction: "higher_is_worse",
      description: { en: "Delay variation", fa: "نوسان در تأخیر" },
      defaultEnabled: false,
      defaults: { warning: 30, critical: 80 },
    },
  ],
};
