import type { MonitoringTypeSchema } from "../monitoring-schema";

// SNMP network-device collector schema. Secrets (community string, v3
// passphrases) are rendered as password inputs and are encrypted at rest by
// the API before they touch the database.
export const snmpSchema: MonitoringTypeSchema = {
  type: "snmp",
  title: { en: "SNMP Device", fa: "دستگاه SNMP" },
  description: {
    en: "Network device collector — interfaces, CPU, memory, sensors",
    fa: "کلکتور تجهیزات شبکه — اینترفیس‌ها، پردازنده، حافظه، سنسورها",
  },
  target: {
    label: { en: "Device address", fa: "آدرس دستگاه" },
    widget: "text",
    key: "host",
    placeholder: "192.168.1.1 or router.example.com",
  },
  execution: {
    minimumIntervalSeconds: 30,
    defaultIntervalSeconds: 300,
    defaultTimeoutMillis: 5000,
    defaultRetries: 1,
  },
  configFields: [
    {
      key: "port",
      widget: "number",
      label: { en: "Port", fa: "پورت" },
      section: "configuration",
      min: 1,
      max: 65535,
      defaultValue: 161,
    },
    {
      key: "version",
      widget: "select",
      label: { en: "SNMP version", fa: "نسخه SNMP" },
      help: {
        en: "SNMPv3 is recommended — it provides authentication and encryption",
        fa: "SNMPv3 پیشنهاد می‌شود — احراز هویت و رمزنگاری فراهم می‌کند",
      },
      section: "configuration",
      options: ["3", "2c", "1"],
      defaultValue: "3",
    },
    {
      key: "community",
      widget: "password",
      label: { en: "Community string", fa: "رشته Community" },
      placeholder: "public",
      section: "configuration",
      visibleWhen: { field: "version", equalsAny: ["1", "2c"] },
    },
    {
      key: "username",
      widget: "text",
      label: { en: "Username", fa: "نام کاربری" },
      section: "configuration",
      visibleWhen: { field: "version", equals: "3" },
    },
    {
      key: "security_level",
      widget: "select",
      label: { en: "Security level", fa: "سطح امنیت" },
      section: "configuration",
      options: ["authNoPriv", "authPriv", "noAuthNoPriv"],
      defaultValue: "authPriv",
      visibleWhen: { field: "version", equals: "3" },
    },
    {
      key: "authentication_protocol",
      widget: "select",
      label: { en: "Authentication protocol", fa: "پروتکل احراز هویت" },
      section: "configuration",
      options: ["SHA-256", "SHA", "MD5"],
      defaultValue: "SHA-256",
      visibleWhen: { field: "security_level", equalsAny: ["authNoPriv", "authPriv"] },
    },
    {
      key: "authentication_secret",
      widget: "password",
      label: { en: "Authentication secret", fa: "رمز احراز هویت" },
      section: "configuration",
      visibleWhen: { field: "security_level", equalsAny: ["authNoPriv", "authPriv"] },
    },
    {
      key: "privacy_protocol",
      widget: "select",
      label: { en: "Privacy protocol", fa: "پروتکل رمزنگاری" },
      section: "configuration",
      options: ["AES-256", "AES", "DES"],
      defaultValue: "AES-256",
      visibleWhen: { field: "security_level", equals: "authPriv" },
    },
    {
      key: "privacy_secret",
      widget: "password",
      label: { en: "Privacy secret", fa: "رمز رمزنگاری" },
      section: "configuration",
      visibleWhen: { field: "security_level", equals: "authPriv" },
    },
    {
      key: "timeout_seconds",
      widget: "number",
      label: { en: "Timeout (s)", fa: "تایم‌اوت (ثانیه)" },
      section: "advanced",
      min: 1,
      max: 30,
      defaultValue: 3,
    },
    {
      key: "retries",
      widget: "number",
      label: { en: "Retries", fa: "تلاش مجدد" },
      section: "advanced",
      min: 0,
      max: 5,
      defaultValue: 1,
    },
    {
      key: "max_repetitions",
      widget: "number",
      label: { en: "Max GETBULK repetitions", fa: "حداکثر تکرار GETBULK" },
      section: "advanced",
      min: 1,
      max: 100,
      defaultValue: 10,
    },
  ],
  healthRules: [
    {
      key: "reachability",
      label: { en: "Device reachable", fa: "دسترس‌پذیری دستگاه" },
      direction: "boolean",
      description: { en: "Device unreachable is critical", fa: "عدم دسترسی به دستگاه بحرانی است" },
      defaultEnabled: true,
    },
    {
      key: "device_health",
      label: { en: "Hardware health", fa: "سلامت سخت‌افزار" },
      direction: "boolean",
      description: { en: "Environmental alarm (temperature/fan/power)", fa: "هشدار محیطی (دما/فن/برق)" },
      defaultEnabled: true,
    },
    {
      key: "cpu_percent",
      label: { en: "CPU utilization", fa: "مصرف پردازنده" },
      unit: "%",
      direction: "higher_is_worse",
      description: { en: "Device CPU utilization", fa: "مصرف پردازنده دستگاه" },
      defaultEnabled: true,
      defaults: { warning: 80, critical: 95 },
    },
    {
      key: "memory_percent",
      label: { en: "Memory utilization", fa: "مصرف حافظه" },
      unit: "%",
      direction: "higher_is_worse",
      description: { en: "Device memory utilization", fa: "مصرف حافظه دستگاه" },
      defaultEnabled: true,
      defaults: { warning: 80, critical: 95 },
    },
    {
      key: "temperature_celsius",
      label: { en: "Temperature", fa: "دما" },
      unit: "°C",
      direction: "higher_is_worse",
      description: { en: "Highest environmental temperature", fa: "بیشترین دمای محیطی" },
      defaultEnabled: false,
      defaults: { warning: 60, critical: 75 },
    },
    {
      key: "interface_oper_status",
      label: { en: "Interface down", fa: "اینترفیس قطع" },
      direction: "boolean",
      description: { en: "A monitored interface is operationally down", fa: "یک اینترفیس مانیتورشده قطع است" },
      defaultEnabled: true,
    },
    {
      key: "interface_utilization_percent",
      label: { en: "Interface utilization", fa: "مصرف پهنای باند" },
      unit: "%",
      direction: "higher_is_worse",
      description: { en: "Highest utilization across monitored interfaces", fa: "بیشترین مصرف بین اینترفیس‌های مانیتورشده" },
      defaultEnabled: false,
      defaults: { warning: 80, critical: 95 },
    },
  ],
};
