import type { MonitoringTypeSchema } from "../monitoring-schema";

export const tlsSchema: MonitoringTypeSchema = {
  type: "tls",
  title: { en: "SSL / TLS", fa: "SSL / TLS" },
  description: { en: "TLS certificate and handshake", fa: "گواهی و دست‌داد TLS" },
  target: {
    label: { en: "Hostname", fa: "نام میزبان" },
    widget: "readonly",
  },
  execution: {
    minimumIntervalSeconds: 10,
    defaultIntervalSeconds: 60,
    defaultTimeoutMillis: 10000,
    defaultRetries: 1,
  },
  configFields: [
    {
      key: "port",
      widget: "number",
      label: { en: "Port", fa: "پورت" },
      section: "configuration",
      min: 1,
      max: 65535,
      defaultValue: 443,
    },
    {
      key: "server_name",
      widget: "text",
      label: { en: "Expected hostname (SNI)", fa: "نام میزبان مورد انتظار (SNI)" },
      help: { en: "Sent as TLS SNI and verified against the certificate", fa: "به‌عنوان SNI ارسال و با گواهی تطبیق داده می‌شود" },
      section: "configuration",
      placeholder: "Defaults to target host",
    },
    {
      key: "verify_tls",
      widget: "switch",
      label: { en: "Verify certificate", fa: "اعتبارسنجی گواهی" },
      help: { en: "Verify the chain and hostname; disabling is not recommended", fa: "اعتبارسنجی زنجیره و نام میزبان؛ غیرفعال کردن توصیه نمی‌شود" },
      section: "configuration",
      defaultValue: true,
    },
    {
      key: "min_tls_version",
      widget: "select",
      label: { en: "Minimum TLS version", fa: "حداقل نسخه TLS" },
      section: "advanced",
      options: ["1.0", "1.1", "1.2", "1.3"],
      defaultValue: "1.2",
    },
  ],
  healthRules: [
    {
      key: "reachability",
      label: { en: "TLS availability", fa: "دسترس‌پذیری TLS" },
      direction: "boolean",
      description: { en: "Handshake or certificate failure is critical", fa: "خطای دست‌داد یا گواهی بحرانی است" },
      defaultEnabled: true,
    },
    {
      key: "certificate_valid",
      label: { en: "Certificate validity", fa: "اعتبار گواهی" },
      direction: "boolean",
      description: { en: "An expired or not-yet-valid certificate is critical", fa: "گواهی منقضی یا هنوز معتبرنشده بحرانی است" },
      defaultEnabled: true,
    },
    {
      key: "hostname_match",
      label: { en: "Hostname match", fa: "تطابق نام میزبان" },
      direction: "boolean",
      description: { en: "Hostname mismatch is critical", fa: "عدم تطابق نام میزبان بحرانی است" },
      defaultEnabled: true,
    },
    {
      key: "chain_valid",
      label: { en: "Chain validation", fa: "اعتبارسنجی زنجیره" },
      direction: "boolean",
      description: { en: "An untrusted chain is critical", fa: "زنجیره نامعتبر بحرانی است" },
      defaultEnabled: true,
    },
    {
      key: "handshake_time_ms",
      label: { en: "Handshake time", fa: "زمان دست‌داد" },
      unit: "ms",
      direction: "higher_is_worse",
      description: { en: "TLS handshake duration", fa: "مدت دست‌داد TLS" },
      defaultEnabled: true,
      defaults: { warning: 500, critical: 2000 },
    },
    {
      key: "certificate_expiry_days",
      label: { en: "Certificate expiry", fa: "انقضای گواهی" },
      unit: "days",
      direction: "lower_is_worse",
      description: { en: "Fewer remaining days is worse", fa: "روزهای باقی‌مانده کمتر بدتر است" },
      defaultEnabled: true,
      defaults: { warning: 30, critical: 14 },
    },
  ],
};
