ALTER TABLE probe_agents ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE probe_agents ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;
ALTER TABLE probe_agents ADD COLUMN IF NOT EXISTS city VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE probe_agents ADD COLUMN IF NOT EXISTS country VARCHAR(100) NOT NULL DEFAULT '';
